spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus, health

server:
  port: 8080
  servlet:
    context-path: /api/v1/profile
springdoc:
    swagger-ui:
      enabled: false
    api-docs:
      path: /docs
